Classes have attained progress. Still need to add functionality to target specific links and to attain equations.
Also:
Need to mess with header files to make it work. Getting error c2011